name: "📝Docs"
description: "문서 관련 작업"
title: "📝 "
labels: ["📝 Documentation"]
body:
  - type: textarea
    attributes:
      label: 📝 작업 설명
      description: 어떤 문서를 작성하거나 수정할 예정인지 설명해 주세요.
      placeholder: API 문서 작성, ISSUE_TEMPLATE 수정 등
    validations:
      required: true
